fixed ArraySpoiler data formatting
hiqdev/hipanel-module-domain pull request #116
Opened 2021-05-21 12:11 UTC by strorch

2021-05-21 20:58 UTC, hiqsol requested changes

2021-05-21 20:58 UTC, hiqsol commented on src/views/domain/_bulkSetContacts.php
> +);
в `$unchangeableZones` должны остаться НЕ изменяемые зоны, а твой код делает наоборот

как на счёт вот так?

```suggestion
$unchangeableZones = array_filter(array_map(
    fn ($model) => $model->isContactChangeable() ? null : $model->domain,
    $models
));
```

надо оставить вариант который легче читается
не могу понять какой :)

2021-05-21 20:58 UTC, hiqsol commented on src/views/domain/_bulkSetNs.php
> +                                    ),
тут тоже, мне кажется читабельнее заменить два колбека на один

2021-05-24 06:44 UTC, strorch commented on src/views/domain/_bulkSetContacts.php
> +);
@SilverFire який легше читається?

2021-05-24 11:09 UTC, SilverFire commented on src/views/domain/_bulkSetNs.php
> +                                    ),
Соглашусь

2021-05-24 11:12 UTC, SilverFire commented on src/views/domain/_bulkSetNs.php
> +                                    ),
```suggestion
                                    'data' => array_filter(array_map(
                                        fn ($model) => $model->isSetNSable() ? $model->domain : null,
                                        $affected
                                    )),
```

2021-05-24 11:13 UTC, SilverFire commented on src/views/domain/_modalPush.php
> +);
```suggestion
$unPushable = array_filter(array_map(
    fn ($model) => $model->canBePushed() ? null : $model->domain,
    $models
));
```

2021-05-24 11:14 UTC, SilverFire commented on src/views/domain/_bulkSetNs.php
> +                                    ),
```suggestion
                                    'data' => array_filter(array_map(
                                        fn ($model) => $model->isSetNSable() ? $model->domain : null,
                                        $affected
                                    )),
```

2021-05-24 11:14 UTC, SilverFire commented on src/views/domain/_bulkSetNs.php
> +                                    ),
```suggestion
                                    'data' => array_filter(array_map(
                                        fn ($model) => $model->isSetNSable() ? null : $model->domain,
                                        $affected
                                    )),
```

2021-05-24 11:15 UTC, SilverFire commented on src/views/domain/_modalNotifyTransferIn.php
> +);
```suggestion
$unNotifiedTransferIn = array_filter(array_map(
    fn ($model) => $model->canSendFOA() ? null : $model->domain,
    $models
));
```

2021-05-24 11:16 UTC, SilverFire approved these changes

2021-05-24 11:21 UTC, SilverFire approved these changes

2021-05-24 11:21 UTC, merged