add interface
hiqdev/hipanel-module-domain pull request #118
Opened 2021-07-05 08:14 UTC by bladeroot

2021-07-08 07:57 UTC, strorch requested changes

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'format' => 'html',
```suggestion
                'format' => 'raw',
```

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                    return Html::a($model->domain, DomainController::getActionUrl('view', $model->domain_id));
```suggestion
                    return Html::a(Html::encode($model->domain), DomainController::getActionUrl('view', $model->domain_id));
```

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                    return Html::tag('span', $model->key_tag);
```suggestion
                    return Html::tag('span', Html::encode($model->key_tag));
```

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function ($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                    return Html::tag('span', $model->digest);
```suggestion
                    return Html::tag('span', Html::encode($model->digest));
```

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/grid/SecdnsGridView.php
> +                'value' => function($model) {
тайпхінт + статік

2021-07-08 07:57 UTC, strorch commented on src/menus/SidebarMenu.php
> +                        'label' => Yii::t('hipanel:domain', 'SecDNS'),
а пермішнов ніяких нема?

2021-07-08 07:57 UTC, strorch commented on src/models/Secdns.php
> +            [['digest'], 'filter', 'filter' => function($value) {
тайпхінт

2021-07-08 07:57 UTC, strorch commented on src/models/Secdns.php
> +                'when' => function($model) {
тайпхінт

2021-07-08 07:57 UTC, strorch commented on src/models/Secdns.php
> +                'when' => function($model) {
тайпхінт

2021-07-14 10:50 UTC, bladeroot commented on src/menus/SidebarMenu.php
> +                        'label' => Yii::t('hipanel:domain', 'SecDNS'),
Окремих нема, як і для доменів

2021-07-14 10:53 UTC, hiqsol commented on src/menus/SidebarMenu.php
> +                        'label' => Yii::t('hipanel:domain', 'SecDNS'),
нет, SecDNS это общедоступный функционал
другой вопрос зачем отдельный пункт меню? по идее это дополнение к обычному DNS

2021-07-14 10:56 UTC, hiqsol approved these changes

2021-07-14 10:56 UTC, merged