add checks for is can change secure and wp options
hiqdev/hipanel-module-domain pull request #68
Opened 2019-07-20 08:18 UTC by bladeroot

2019-07-20 08:23 UTC, SilverFire requested changes

2019-07-20 08:23 UTC, SilverFire commented on src/models/Domain.php
> +    public function isWPChangeable()
```suggestion
    public function isWPChangeable(): bool
```

2019-07-20 08:23 UTC, SilverFire commented on src/models/Domain.php
> +    public function isSecureChangeable()
```suggestion
    public function isSecureChangeable(): bool
```

2019-07-20 08:23 UTC, SilverFire commented on src/models/Domain.php
> +    public function getTopLevelZone()
```suggestion
    public function getTopLevelZone(): string
```

2019-07-20 08:23 UTC, SilverFire commented on src/models/Domain.php
> +    public function isZone($zones, $zone = null)
Я бы лучше завёл отдельный метод `isTopLevelZone()`

2019-07-20 08:23 UTC, SilverFire commented on src/grid/DomainGridView.php
> +                        'readonly' => !(bool)$model->isWPChangeable(),
```suggestion
                        'readonly' => !$model->isWPChangeable(),
```

Возвращаемый тип – строго буль, приводить не нужно

2019-07-20 08:23 UTC, SilverFire commented on src/grid/DomainGridView.php
> +                        'readonly' => !(bool) $model->isSecureChangeable(),
```suggestion
                        'readonly' => !$model->isSecureChangeable(),
```

2019-07-20 08:45 UTC, bladeroot commented on src/models/Domain.php
> +    public function isZone($zones, $zone = null)
Для чего? все равно там зона вычислялась, но правда как то было не очень.

2019-07-21 07:34 UTC, SilverFire commented on src/models/Domain.php
> +    public function isZone($zones, $zone = null)
Во-первых это нарушает целостность метода: допустим, есть объект `Domain(domain='example.com')`, а ты можешь вызвать вызываешь `$domain->isZone(['ru'], 'net')`. Зачем-то зона переопределилась и получился непредсказуемый результат выполнения.

Во-вторых это Code smell, почитай https://softwareengineering.stackexchange.com/questions/147977/is-it-wrong-to-use-a-boolean-parameter-to-determine-behavior. Увеличивается когнитивная сложность метода

2019-07-29 10:17 UTC, hiqsol requested changes

2019-07-29 10:17 UTC, hiqsol commented on src/models/Domain.php
> +    public function isZone($zones, $zone = null)
херню вы оба пишите
`isZone` просто должен проверять по другому, надо проверять что конец домена совпадает с переданными зонами
типа так:

```php
foreach ($zones as $zone) {
    if (substr($this->domain, -(strlen($zone) + 1)) === ".$zone") {
        return true;
    }
}
return false;
```

2019-07-29 10:22 UTC, hiqsol commented on src/models/Domain.php
> +    public function isZone($zones, $zone = null)
не, давай так
то что я написал, назови `isLastZone()`
а `isZone()` оставь как было

2019-07-29 10:23 UTC, hiqsol commented on src/grid/DomainGridView.php
> +                'pluginOptions' => function($model) {
type hinting

2019-07-29 10:46 UTC, hiqsol approved these changes

2019-07-29 10:46 UTC, hiqsol commented on src/grid/DomainGridView.php
> +                'pluginOptions' => function($model) {
type hinting

2019-07-29 10:47 UTC, merged